name: Build & Test

on: push

jobs:
  build-app-e2e-tests:
    runs-on: ubuntu-latest
    #  run job only on master branch
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble app apk
        run: ./gradlew app:assembleDebug

      - name:  Assemble test apk
        run: ./gradlew app:assembleDebugAndroidTest

      - name: Store Google Service Account
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        run: echo $GCLOUD_AUTH > ${HOME}/gcloud-service-key.json

      - name: Login to Google Cloud
        run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

      - name: Set current project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run 
          --type instrumentation
          --app app/build/outputs/apk/debug/app-debug.apk
          --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          --device model=a03s,version=33,locale=en,orientation=portrait

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew unitTests

  feature-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run feature tests
        run: ./gradlew featureTests



